### ISSUE TITLE
布局问题

### ISSUE THREAD

**Issue by SEALiu** [SEALiu/memo#2]
在toolbar下面多出一块(深蓝色的部分)，我不知道是什么？该怎么去掉

![issues 2](https://cloud.githubusercontent.com/assets/4458327/16450952/99d777c8-3e32-11e6-83ab-c897834d57aa.png)

**涉及到的布局文件**

- [fragment_main.xml](https://github.com/SEALiu/memo/blob/master/app/src/main/res/layout/fragment_main.xml)
- [content_main.xml](https://github.com/SEALiu/memo/blob/master/app/src/main/res/layout/content_main.xml)
- [app_bar_main.xml](https://github.com/SEALiu/memo/blob/master/app/src/main/res/layout/app_bar_main.xml)

**从上至下以此为包含关系，即：下面的包含上面的**

**Comment by PrinceChou** [comment]
我来和你做！

**Comment by SEALiu** [comment]
@PrinceChou 这个是参加[StudyJams](http://www.studyjamscn.com/)活动的项目，你也是吗？

**Comment by SEALiu** [comment]
好的，那你先看看代码。我是初学，可能写的比较乱

**Comment by SEALiu** [comment]
解决了，原因是我嵌套了两个 `CoordinatorLayout`
